Repository OpenSCAP/oval-graph, pull requests merged in 2020-12, with the labels that each got.

#155 Automatically closes the web browser in tests
  oval_graph/client.py
  tests/test_arf_to_hml.py
  tests/test_command_arf_to_graph.py
  tests/test_command_json_to_graph.py
  tests/test_json_to_html.py
Labels: enhancement

#161 Enhances test suite
  .flake8
  .gitignore
  README.md
  docs/GUIDE.md
  test_suite_requirements.txt
  tests/test_command_arf_to_graph.py
  tests/test_command_arf_to_json.py
  tests/test_command_json_to_graph.py
  tox.ini
Labels: documentation, enhancement

#163 Fix loading of ARF results when comment node is missing.
  oval_graph/_xml_parser_comments.py
Labels: bug-fix
